### PR TITLE
hid api key 

### PR DESCRIPTION
**Pull request by sora-san45**

### CODE REVIEW

**Comment by imkrishnasarathi** [comment]
Hey, I think you forgot to create config.js or json

**Comment by sora-san45** [comment]
> Hey, I think you forgot to create config.js or json

I added it to the .gitignore file. But if I add config.js wouldn't it still expose the api key

**Comment by imkrishnasarathi** [comment]
so what do you think? How should I continue adding the api? any advices ? :)

**Comment by sora-san45** [comment]
> so what do you think? How should I continue adding the api? any advices ? :)

Another solution I saw was to create a proxy server using node and express

**Comment by imkrishnasarathi** [comment]
Can you do that? That would be great.

**Comment by sora-san45** [comment]
Yes I will try 👍

**Comment by imkrishnasarathi** [comment]
Thanks! It is great of you trying to improve this project :)

**Pull request closed without merging**
